/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface IRendererInterface extends ethers.utils.Interface {
  functions: {
    "getGearName(uint256)": FunctionFragment;
    "getRarity(uint256)": FunctionFragment;
    "render(uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getGearName",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRarity",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "render",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "getGearName",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getRarity", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "render", data: BytesLike): Result;

  events: {};
}

export class IRenderer extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IRendererInterface;

  functions: {
    getGearName(
      mgear: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getRarity(
      mgear: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[number]>;

    render(
      mgear: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string] & { svg: string }>;
  };

  getGearName(
    mgear: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getRarity(mgear: BigNumberish, overrides?: CallOverrides): Promise<number>;

  render(mgear: BigNumberish, overrides?: CallOverrides): Promise<string>;

  callStatic: {
    getGearName(
      mgear: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRarity(mgear: BigNumberish, overrides?: CallOverrides): Promise<number>;

    render(mgear: BigNumberish, overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    getGearName(
      mgear: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRarity(
      mgear: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    render(mgear: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    getGearName(
      mgear: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRarity(
      mgear: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    render(
      mgear: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
